file = open("notes.txt", "w")
file.write("python is a powerful programming language.\n ")
file.write("It is easy to learn and fun to use.\n")
file.close()
print("Inital data written to 'notes.txt'.")
file = open("notes.txt", "a")
file.write("File handling is a important concept in python.\n")
file.write("Always close your files properly! \n")
file.close()
print("New data appended to 'notes.txt'. ")
file = open("notes.txt", "r")
content = file.read()
print("\n file content: \n")
print(content)
file.close()
lines = content.splitlines()
words =content.split()
characters = len(content)
print(f"total lines: {len(lines)}")
print(f"total words: {len(words)}")
print(f"total characters: {characters}")