source = open("source.txt", "w")
source.write("This is a original file. \n")
source.write("We will copy this text into another file.\n ")
source.close()
print("Data written to 'source.txt'.")
source = open("source.txt","r")
data = source.read()
source.close
destination = open("copy.txt", "w")
destination.write(data)
destination.close()
print("Data copied from 'source.txt' to 'copy.txt' successfully")
destination = open("copy.txt", "r")
print("\n copied file content:\n")
destination.close()